from __future__ import annotations

import logging
from collections.abc import Iterable
from pathlib import Path

from aurora_translator.shared.logging import log_timing
from aurora_translator.sources.auroradb.block import split_reserved

from .commands import AAFCommand, AAFCommandFile, CommandOption
from .lexer import is_option_token, tokenize_command


logger = logging.getLogger("aurora_translator.targets.auroradb.aaf")


def parse_command_file(path: str | Path) -> AAFCommandFile:
    file_path = Path(path).expanduser().resolve()
    with file_path.open("r", encoding="utf-8-sig") as handle:
        return _parse_command_lines(
            handle,
            source_path=file_path,
            source_label=str(file_path),
            timing_name="parse AAF command file",
        )


def parse_command_text(text: str, *, source: str = "memory") -> AAFCommandFile:
    source_path = Path(source)
    return _parse_command_lines(
        text.splitlines(),
        source_path=source_path,
        source_label=source,
        timing_name="parse AAF command text",
    )


def parse_command_lines(
    lines: Iterable[str], *, source: str = "memory"
) -> AAFCommandFile:
    source_path = Path(source)
    return _parse_command_lines(
        lines,
        source_path=source_path,
        source_label=source,
        timing_name="parse AAF command lines",
    )


def parse_exported_command_lines(
    lines: Iterable[str], *, source: str = "memory"
) -> AAFCommandFile:
    """Parse AAF lines emitted by this exporter with a lighter parser.

    The normal parser remains the compatibility path for user-provided AAF.
    This fast path is intentionally limited to the deterministic command
    surface generated by targets/auroradb/exporter.py.
    """

    source_path = Path(source)
    commands: list[AAFCommand] = []
    diagnostics: list[str] = []
    with log_timing(
        logger, "parse exported AAF command lines", source=source, level=logging.DEBUG
    ):
        for line_no, raw in enumerate(lines, start=1):
            try:
                command = parse_exported_command_line(
                    raw, line_no=line_no, source=source_path
                )
            except ValueError as exc:
                diagnostics.append(f"{source}:{line_no}: {exc}")
                continue
            if command is not None:
                commands.append(command)
    logger.debug(
        "Parsed exported AAF commands %s with commands:%s diagnostics:%s",
        source,
        len(commands),
        len(diagnostics),
    )
    return AAFCommandFile(source_path, commands, diagnostics)


def _parse_command_lines(
    lines: Iterable[str],
    *,
    source_path: Path,
    source_label: str,
    timing_name: str,
) -> AAFCommandFile:
    commands: list[AAFCommand] = []
    diagnostics: list[str] = []
    with log_timing(logger, timing_name, source=source_label, level=logging.DEBUG):
        for line_no, raw in enumerate(lines, start=1):
            try:
                command = parse_command_line(raw, line_no=line_no, source=source_path)
            except ValueError as exc:
                diagnostics.append(f"{source_label}:{line_no}: {exc}")
                continue
            if command is not None:
                commands.append(command)
    logger.debug(
        "Parsed AAF commands %s with commands:%s diagnostics:%s",
        source_label,
        len(commands),
        len(diagnostics),
    )
    return AAFCommandFile(source_path, commands, diagnostics)


def parse_exported_command_line(
    raw: str, *, line_no: int = 0, source: Path | None = None
) -> AAFCommand | None:
    line = raw.strip()
    if not line or line.startswith("#"):
        return None

    parts = line.split(None, 2)
    if len(parts) < 2:
        return parse_command_line(raw, line_no=line_no, source=source)
    options = _parse_exported_options(parts[2] if len(parts) > 2 else "")
    if options is None:
        return parse_command_line(raw, line_no=line_no, source=source)
    return AAFCommand(
        words=[parts[0].casefold(), parts[1].casefold()],
        options=options,
        raw=raw,
        line_no=line_no,
        source=source,
    )


def parse_command_line(
    raw: str, *, line_no: int = 0, source: Path | None = None
) -> AAFCommand | None:
    line = raw.strip()
    if not line or line.startswith("#"):
        return None
    tokens = tokenize_command(line)
    if not tokens:
        return None

    words: list[str] = []
    index = 0
    while index < len(tokens):
        token = tokens[index]
        if is_option_token(token, line):
            break
        words.append(token.casefold())
        index += 1

    options: list[CommandOption] = []
    active: CommandOption | None = None
    for token in tokens[index:]:
        if is_option_token(token, line):
            active = CommandOption(token, [])
            options.append(active)
        elif active is not None:
            active.values.append(token)

    if not words:
        raise ValueError(f"Missing command words: {raw}")
    return AAFCommand(
        words=words, options=options, raw=raw, line_no=line_no, source=source
    )


def _parse_exported_options(rest: str) -> list[CommandOption] | None:
    options: list[CommandOption] = []
    index = 0
    length = len(rest)
    while index < length:
        while index < length and rest[index].isspace():
            index += 1
        if index >= length:
            break
        if rest[index] != "-":
            return None

        option_start = index
        index += 1
        while index < length and not rest[index].isspace():
            index += 1
        option_name = rest[option_start:index]
        if len(option_name) <= 1 or option_name[1].isdigit():
            return None

        values: list[str] = []
        while index < length:
            while index < length and rest[index].isspace():
                index += 1
            if index >= length or _is_exported_option_start(rest, index):
                break
            parsed = _read_exported_option_value(rest, index)
            if parsed is None:
                return None
            value, index = parsed
            values.extend(_exported_option_values(option_name, value))
        options.append(CommandOption(option_name, values))
    return options


def _is_exported_option_start(text: str, index: int) -> bool:
    return (
        text[index] == "-"
        and index + 1 < len(text)
        and not text[index + 1].isdigit()
        and (index == 0 or text[index - 1].isspace())
    )


def _read_exported_option_value(text: str, index: int) -> tuple[str, int] | None:
    if text[index] != "<":
        end = index
        while end < len(text) and not text[end].isspace():
            end += 1
        return text[index:end], end

    value_start = index + 1
    cursor = value_start
    in_quote = False
    escaped = False
    while cursor < len(text):
        char = text[cursor]
        if in_quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_quote = False
        elif char == '"':
            in_quote = True
        elif char == ">":
            return text[value_start:cursor], cursor + 1
        cursor += 1
    return None


def _exported_option_values(option_name: str, value: str) -> list[str]:
    if value == "":
        return [""]
    option_key = option_name.casefold()
    if option_key == "-via" and "," not in value and " " not in value:
        return [value]
    if option_key not in {"-layerstack", "-via"}:
        return [value]
    return split_reserved(
        value,
        delimiters=" ,",
        reserve_pairs=(("(", ")"), ("[", "]"), ("{", "}"), ('"', '"')),
    )
